#!/bin/sh /etc/rc.common
# Copyright (c) 20022 Zcoder

START=99
USE_PROCD=1

screen_file="/root/sync/screen.log" 
screen_name="sync"

section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
   echo "AUTOSYNC service enable.."
	[ $enabled -gt 0 ]
}


start_service() {
    if screen -list | grep "$screen_name"; then
        echo "Session already exists.. "
        screen -S $screen_name -X quit
        echo "Screen exited.."
    fi

    if [ -f "$screen_file" ]; then
        rm $screen_file 
        echo "Delete log screen $screen_file.." 
    fi
    screen -dmS $screen_name -L -Logfile $screen_file sync
    echo  "AUTOSYNC service ruining...."
}

stop_service() {
   if [ -f "$screen_file" ]; then
        rm $screen_file 
        echo "Delete screen $screen_file.." 
    fi
    screen -S $screen_name -X quit
    echo  "AUTOSYNC service terminate...."
   
}


reload_service() {
	stop
	start
}
